import Image from 'next/image'

import { Container } from '@/components/Container'
import backgroundImage from '@/images/background-faqs.jpg'

const faqs = [
  [
    {
      question: 'Is SmartResume.ai free to use?',
      answer:
        'Yes, you can create a professional resume for free. We also offer premium features like cover letter generation and advanced analytics.',
    },
    {
      question: 'What makes SmartResume.ai different from other resume builders?',
      answer:
        'Our AI-powered platform not only helps you build a resume in seconds but also matches you with relevant job openings in real-time.',
    },
    {
      question: 'How does the AI job matching work?',
      answer:
        'Our AI analyzes your resume and compares it against thousands of job listings from multiple sources to find the best matches for your skills and experience.',
    },
  ],
  [
    {
      question: 'Is my data secure with SmartResume.ai?',
      answer:
        'Yes, we take data privacy very seriously. Your personal information is encrypted and securely stored. We will never share your data without your consent.',
    },
    {
      question: 'Can I edit the resume generated by the AI?',
      answer:
        'Absolutely. You have full control to edit and customize every section of your resume in our live editor before exporting it.',
    },
    {
      question: 'What formats can I export my resume in?',
      answer:
        'You can export your resume in PDF and DOCX formats, ensuring compatibility with all online application systems.',
    },
  ],
  [
    {
      question: 'How quickly can I create a resume?',
      answer:
        'With our AI generator, you can have a professional, ATS-optimized resume ready in as little as 30 seconds by simply describing your experience.',
    },
    {
      question: 'Do you offer career coaching?',
      answer:
        'Our premium plan includes AI-powered career coaching, offering interview preparation, salary negotiation advice, and career path recommendations.',
    },
    {
      question: 'I need a cover letter, can you help?',
      answer:
        'Yes, our AI can generate a tailored cover letter for any job application, highlighting your most relevant skills and experiences.',
    },
  ],
]

export function Faqs() {
  return (
    <section
      id="faq"
      aria-labelledby="faq-title"
      className="relative overflow-hidden bg-slate-50 py-20 sm:py-32"
    >
      <Image
        className="absolute top-0 left-1/2 max-w-none translate-x-[-30%] -translate-y-1/4"
        src={backgroundImage}
        alt=""
        width={1558}
        height={946}
        unoptimized
      />
      <Container className="relative">
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2
            id="faq-title"
            className="font-display text-3xl tracking-tight text-slate-900 sm:text-4xl"
          >
            Frequently asked questions
          </h2>
          <p className="mt-4 text-lg tracking-tight text-slate-700">
            If you can’t find what you’re looking for, email our support team
            and if you’re lucky someone will get back to you.
          </p>
        </div>
        <ul
          role="list"
          className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 lg:max-w-none lg:grid-cols-3"
        >
          {faqs.map((column, columnIndex) => (
            <li key={columnIndex}>
              <ul role="list" className="flex flex-col gap-y-8">
                {column.map((faq, faqIndex) => (
                  <li key={faqIndex}>
                    <h3 className="font-display text-lg/7 text-slate-900">
                      {faq.question}
                    </h3>
                    <p className="mt-4 text-sm text-slate-700">{faq.answer}</p>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  )
}
